-- Ejecuta este script solo si la tabla `eventos` aún no existe en Supabase.
-- La aplicación habla únicamente con el backend; no expongas SUPABASE_KEY en Vercel.
create table if not exists public.eventos (
  id bigint generated by default as identity primary key,
  titulo text not null check (char_length(trim(titulo)) between 3 and 120),
  descripcion text check (descripcion is null or char_length(descripcion) <= 500),
  fecha date not null,
  creado_en timestamptz not null default timezone('utc', now())
);

create index if not exists eventos_fecha_idx on public.eventos (fecha);

-- Si RLS está activado, la clave de servicio usada exclusivamente en Render
-- puede insertar y leer. No añadas esa clave al frontend.
